function n(c,a,b,d){c.h.fa(c.V,a,b,d)}function r(c,a,b,d){c.h.m?n(c,a,b,d):c.h.Ib()._OnMessageFromDOM({type:"event",component:c.V,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function t(c,a,b){c.h.i(c.V,a,b)}function aa(c,a){for(const [b,d]of a)t(c,b,d)}window.Ua=class{constructor(c,a){this.h=c;this.V=a}Ra(){}};window.rc=class{constructor(){}};"use strict";class ba{constructor(c){this.W=c;this.Ba=!1;this.Ea=!0;this.X=this.v=this.Na=-1}}
function ca(c,a){const b=a.elementId,d=c.Ta(b,a),e=new ba(d);c.F.set(b,e);d.style.boxSizing="border-box";d.style.display="none";e.Ea=!!a.isVisible;d.addEventListener("focus",()=>{u(c,"elem-focused",b)});d.addEventListener("blur",()=>{u(c,"elem-blurred",b)});const f=a.htmlIndex;e.Na=f;e.X=a.htmlZIndex;c.J&&(a=c.h.qa(f),e.v=a,c.h.ea(a).appendChild(d))}function da(c,a){t(c,"get-element",b=>{const d=v(c,b.elementId);return a(d,b)})}
function v(c,a){c=c.F.get(a);if(!c)throw Error(`no element with id ${a}`);return c.W}function u(c,a,b,d){d||(d={});d.elementId=b;n(c,a,d)}
window.pa=class extends self.Ua{constructor(c){super(c,"sliderbar");this.F=new Map;this.J=!0;aa(this,[["create",a=>ca(this,a)],["destroy",a=>{a=a.elementId;const b=v(this,a);this.J&&b.parentElement.removeChild(b);this.F.delete(a)}],["set-visible",a=>{if(this.J){var b=this.F.get(a.elementId),d=b.W;b.Ba?d.style.display=a.isVisible?"":"none":b.Ea=!!a.isVisible}}],["update-position",a=>{if(this.J){var b=this.F.get(a.elementId),d=b.W,e=this.h;d.style.left=a.left+"px";d.style.top=a.top+"px";d.style.width=
a.width+"px";d.style.height=a.height+"px";var f=a.fontSize;null!==f&&(d.style.fontSize=f+"em");f=a.htmlIndex;b.Na=f;f=e.qa(f);f!==b.v&&(d.remove(),e.ea(f).appendChild(d),b.v=f,e.ya());a=a.htmlZIndex;a!==b.X&&(b.X=a,e.ya());b.Ba||(b.Ba=!0,b.Ea&&(d.style.display=""))}}],["update-state",a=>{const b=v(this,a.elementId);this.ta(b,a)}],["focus",a=>{const b=v(this,a.elementId);a.focus?b.focus():b.blur()}],["set-css-style",a=>{const b=v(this,a.elementId),d=a.prop;a=a.val;d.startsWith("--")?b.style.setProperty(d,
a):b.style[d]=a}],["set-attribute",a=>{v(this,a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{v(this,a.elementId).removeAttribute(a.name)}]]);da(this,a=>a)}Ta(){throw Error("required override");}ta(){throw Error("required override");}};"use strict";const w=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),x=/android/i.test(navigator.userAgent),ea=/safari/i.test(navigator.userAgent)&&!/(chrome|chromium|edg\/|OPR\/|nwjs)/i.test(navigator.userAgent);let y=0;
function z(c){const a=document.createElement("script");a.async=!1;a.type="module";return c.hc?new Promise(b=>{const d="c3_resolve_"+y;++y;self[d]=b;a.textContent=c.lc+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((b,d)=>{a.onload=b;a.onerror=d;a.src=c;document.head.appendChild(a)})}
async function fa(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let c=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){c=!0}}),b=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return c&&b}catch(c){return console.warn("Error feature detecting worker mode: ",c),!1}}let A=new Audio;
const ha={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};A=null;async function ia(c){c=await B(c);return(new TextDecoder("utf-8")).decode(c)}
function B(c){return new Promise((a,b)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>b(e);d.readAsArrayBuffer(c)})}const C=[];let D=0;window.RealFile=window.File;const E=[],F=new Map,G=new Map;let ja=0;const H=[];self.runOnStartup=function(c){if("function"!==typeof c)throw Error("runOnStartup called without a function");H.push(c)};const I=new Set(["cordova","playable-ad","instant-games"]);let ka=!1;
window.sa=class c{constructor(a){this.m=a.nc;this.$=null;this.l="";this.M=a.kc;this.ca={};this.Ga=this.O=null;this.K=[];this.G=null;this.nb=!0;this.j=[];this.Ka=[];this.La=!1;this.pb=()=>this.Gb();this.mb=!1;this.Y=null;this.L=-1;this.cc=()=>this.Rb();this.aa=new Set;this.Oa=null;this.qb=[];this.g=a.rb;this.Da="file"===location.protocol.substr(0,4);if("playable-ad"===this.g||"instant-games"===this.g)this.m=!1;ea&&(this.m=!1);if("cordova"===this.g&&this.m&&x){const b=/Chrome\/(\d+)/i.exec(navigator.userAgent);
b&&90<=parseInt(b[1],10)||(this.m=!1)}this.H()?self.chrome.webview.addEventListener("message",b=>this.eb(b.data)):"macos-wkwebview"===this.g&&(self.C3WrapperOnMessage=b=>this.eb(b));this.ia=this.A=null;"html5"!==this.g||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.i("canvas","update-size",b=>this.Vb(b));this.i("canvas","set-html-layer-count",
b=>this._OnSetHTMLLayerCount(b));this.i("canvas","cleanup-html-layers",()=>this.Mb());this.i("runtime","cordova-fetch-local-file",b=>this.Nb(b));this.i("runtime","create-job-worker",()=>this.Ob());this.i("runtime","send-wrapper-extension-message",b=>this.Ub(b));"cordova"===this.g?document.addEventListener("deviceready",()=>this.bb(a)):this.bb(a)}tb(){return this.j[0].canvas}qa(a){return Math.min(a,this.j.length-1)}ea(a){if(0>a||a>=this.j.length)throw new RangeError("invalid canvas layer");return this.j[a].da}xb(){return w&&
"cordova"===this.g}S(){const a=navigator.userAgent;return w&&I.has(this.g)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}vb(){return x}Va(){return x&&I.has(this.g)}Wa(){return"windows-webview2"===this.g||!!("preview"===this.g&&window.chrome&&window.chrome.webview&&window.chrome.webview.postMessage)}H(){return this.Wa()||"xbox-uwp-webview2"===this.g}async bb(a){this.m&&!await fa()&&(this.m=!1);"macos-wkwebview"===this.g?this.T({type:"ready"}):this.H()&&(this.Yb(),this.qb=(await this.Lb()).registeredComponentIds);
if("playable-ad"===this.g){this.A=self.c3_base64files;this.ia={};await this.Db();for(let d=0,e=a.P.length;d<e;++d){var b=a.P[d];this.ia.hasOwnProperty(b)?a.P[d]={hc:!0,lc:this.ia[b]}:this.A.hasOwnProperty(b)&&(a.P[d]=URL.createObjectURL(this.A[b]))}a.ma=[]}if("nwjs"===this.g&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.Xa(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.jc?this.l=a.jc:(b=location.origin,this.l=("null"===b?"file:///":b)+location.pathname,b=this.l.lastIndexOf("/"),
-1!==b&&(this.l=this.l.substr(0,b+1)));a.pc&&(this.ca=a.pc);b=new MessageChannel;this.$=b.port1;this.$.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Qb(d));this.Y=new self.yb(this);await la(this.Y);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",
d)}this.m?await this.Kb(a,b.port2):await this.Jb(a,b.port2)}va(a){a=this.ca.hasOwnProperty(a)?this.ca[a]:a.endsWith("/workermain.js")&&this.ca.hasOwnProperty("workermain.js")?this.ca["workermain.js"]:"playable-ad"===this.g&&this.A.hasOwnProperty(a)?this.A[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async oa(a,b,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.g&&this.Da)return a=await this.na(d.fc?a:this.M+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),
d);a=new URL(a,b);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}u(){return Math.max(window.innerWidth,1)}o(){return Math.max(window.innerHeight,1)}ra(){return this.H()||(new Set(["cordova","nwjs","macos-wkwebview"])).has(this.g)?"standalone":window.matchMedia("(display-mode: fullscreen)").matches?"fullscreen":window.matchMedia("(display-mode: standalone)").matches?
"standalone":window.matchMedia("(display-mode: minimal-ui)").matches?"minimal-ui":navigator.standalone?"standalone":"browser"}ab(a){var b=this.l,d=location.href,e=this.u(),f=this.o(),h=this.ra(),g=window.devicePixelRatio,k=c.R(),l=a.uc,m=window.cr_previewImageBlobs||this.A,p=window.cr_previewProjectFileBlobs,q=window.cr_previewProjectFiles,xa=window.cr_swClientId||"";a=a.rb;var ya=(new URLSearchParams(self.location.search)).has("debug"),K=this.Y;return{runtimeBaseUrl:b,previewUrl:d,windowInnerWidth:e,
windowInnerHeight:f,cssDisplayMode:h,devicePixelRatio:g,isFullscreen:k,projectData:l,previewImageBlobs:m,previewProjectFileBlobs:p,previewProjectFileSWUrls:q,swClientId:xa,exportType:a,isDebug:ya,ife:!!self.tc,jobScheduler:{inputPort:K.Ca,outputPort:K.Ja,maxNumWorkers:K.ac},supportedAudioFormats:ha,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.M+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.M+"opus.wasm.wasm",isFileProtocol:this.Da,isiOSCordova:this.xb(),isiOSWebView:this.S(),
isWindowsWebView2:this.Wa(),isAnyWebView2Wrapper:this.H(),wrapperComponentIds:this.qb,isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Kb(a,b){const d=this.va(a.oc);"preview"===this.g?(this.O=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,m)=>{const p=q=>{this.O.removeEventListener("message",p);q.data&&"ok"===q.data.type?l():m()};this.O.addEventListener("message",p);this.O.postMessage({type:"construct-worker-init","import":(new URL(d,this.l)).toString()})})):
this.O=await this.oa(d,this.l,{type:"module",name:"Runtime",fc:!0});const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);const h=document.createElement("div");h.className="c3htmlwrap";document.body.appendChild(h);this.j.push({canvas:e,da:h});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let g=a.ma||[],k=a.P;g=await Promise.all(g.map(l=>this.I(l)));k=await Promise.all(k.map(l=>this.I(l)));
if("cordova"===this.g)for(let l=0,m=a.la.length;l<m;++l){const p=a.la[l],q=p[0];if(q===a.Pa||"scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))p[1]=await this.I(q)}this.O.postMessage(Object.assign(this.ab(a),{type:"init-runtime",isInWorker:!0,messagePort:b,canvas:f,workerDependencyScripts:g,engineScripts:k,projectScripts:a.la,mainProjectScript:a.Pa,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[b,f,...ma(this.Y)]);this.K=E.map(l=>new l(this));this.$a();J(e);L(h);na(this.G);self.c3_callFunction=
(l,m)=>{var p=this.G;return p.h.zb(p.V,{name:l,params:m})};"preview"===this.g&&(self.goToLastErrorScript=()=>this.fa("runtime","go-to-last-error-script"))}async Jb(a,b){const d=document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.j.push({canvas:d,da:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.K=E.map(g=>new g(this));this.$a();
J(d);L(e);e=a.P.map(g=>"string"===typeof g?(new URL(g,this.l)).toString():g);if(Array.isArray(a.ma)){var f=[...a.ma].map(g=>g instanceof Blob?URL.createObjectURL(g):g);e.unshift(...f)}e=await Promise.all(e.map(g=>this.I(g)));await Promise.all(e.map(g=>z(g)));e=self.C3_ProjectScriptsStatus;f=a.Pa;const h=a.la;for(let [g,k]of h)if(k||(k=g),g===f)try{k=await this.I(k),await z(k),"preview"!==this.g||e[g]||this.fb(g,"main script did not run to completion")}catch(l){this.fb(g,l)}else if("scriptsInEvents.js"===
g||g.endsWith("/scriptsInEvents.js"))k=await this.I(k),await z(k);"preview"===this.g&&"object"!==typeof self.qc.sc?(this.ha(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.ab(a),{isInWorker:!1,messagePort:b,canvas:d,runOnStartupFunctions:H}),na(this.G),this.cb(),this.Ga=self.C3_CreateRuntime(a),
await self.C3_InitRuntime(this.Ga,a))}fb(a,b){this.ha();console.error(`[Preview] Failed to load project main script (${a}): `,b);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}cb(){this.ha()}ha(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Ob(){const a=await oa(this.Y);return{outputPort:a,transferables:[a]}}Vb(a){if(!this.mb){var b=
a.styleWidth+"px",d=a.styleHeight+"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:h,da:g}of this.j)h.style.width=b,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,g.style.width=b,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,this.nb&&(h.style.display="",g.style.display="");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.nb=!1}}_OnSetHTMLLayerCount(a){var b=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const h=
a.marginLeft+"px",g=a.marginTop+"px";a=[];const k=[];if(b<this.j.length)for(;this.j.length>b;){const {canvas:l,da:m}=this.j.pop();m.remove();this.m&&!d?this.Ka.push(l):l.remove()}else if(b>this.j.length)for(let l=0,m=b-this.j.length;l<m;++l)b=document.createElement("canvas"),b.classList.add("c3overlay"),this.m?(d=b.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(b),document.body.appendChild(b),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),
b.style.width=e,b.style.height=f,b.style.marginLeft=h,b.style.marginTop=g,d.style.width=e,d.style.height=f,d.style.marginLeft=h,d.style.marginTop=g,J(b),L(d),this.j.push({canvas:b,da:d});for(const l of this.K)if(l instanceof window.pa&&l.J)for(const m of l.F.values())e=l.h.qa(m.Na),f=m.v,-1!==e&&-1!==f&&e!==f&&(f=m.W,f.remove(),l.h.ea(e).appendChild(f),m.v=e);this.ya();return{addedCanvases:a,transferables:k}}Mb(){for(const a of this.Ka)a.remove();this.Ka.length=0}ya(){this.La||(this.La=!0,this.Xa(this.pb))}Gb(){this.Xb(this.pb);
this.La=!1;let a=[];for(var b of this.K)if(b instanceof window.pa){var d=b.J?[...b.F.values()]:null;d&&a.push(...d)}a.sort((h,g)=>{const k=h.v,l=g.v;return k!==l?k-l:h.X-g.X});let e=d=b=0,f=a.length;for(;e<f;++e){const h=a[e];h.v!==b&&(this.Za(b,a.slice(d,e)),b=h.v,d=e)}d<e&&this.Za(b,a.slice(d,e))}Za(a,b){if(!(1>=b.length||a>=this.j.length)){b=b.map(k=>k.W);var d=new Set(b);a=this.ea(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,h=Math.min(b.length,e.length);f<h&&b[f]===e[f];++f);for(var g=
f;g<h;++g)e[g].remove();for(g=f;g<h;++g)a.appendChild(b[g])}}Ib(){if(this.m)throw Error("not available in worker mode");return this.Ga}fa(a,b,d,e){this.$.postMessage({type:"event",component:a,handler:b,dispatchOpts:e||null,data:d,responseId:null},void 0)}zb(a,b){const d=ja++,e=new Promise((f,h)=>{G.set(d,{resolve:f,reject:h})});this.$.postMessage({type:"event",component:a,handler:"js-invoke-function",dispatchOpts:null,data:b,responseId:d},void 0);return e}_OnMessageFromRuntime(a){const b=a.type;if("event"===
b)return this.Pb(a);if("result"===b)this.Sb(a);else if("runtime-ready"===b)this.Tb();else if("alert-error"===b)this.ha(),alert(a.message);else if("creating-runtime"===b)this.cb();else throw Error(`unknown message '${b}'`);}Pb(a){const b=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=F.get(b))if(a=a.get(d)){var h=null;try{h=a(e)}catch(g){console.error(`Exception in '${b}' handler '${d}':`,g);null!==f&&this.ga(f,!1,""+g);return}if(null===f)return h;h&&h.then?h.then(g=>this.ga(f,!0,g)).catch(g=>
{console.error(`Rejection from '${b}' handler '${d}':`,g);this.ga(f,!1,""+g)}):this.ga(f,!0,h)}else console.warn(`[DOM] No handler '${d}' for component '${b}'`);else console.warn(`[DOM] No event handlers for component '${b}'`)}ga(a,b,d){let e;d&&d.transferables&&(e=d.transferables);this.$.postMessage({type:"result",responseId:a,isOk:b,result:d},e)}Sb(a){const b=a.responseId,d=a.isOk;a=a.result;const e=G.get(b);d?e.resolve(a):e.reject(a);G.delete(b)}i(a,b,d){let e=F.get(a);e||(e=new Map,F.set(a,e));
if(e.has(b))throw Error(`[DOM] Component '${a}' already has handler '${b}'`);e.set(b,d)}static Qa(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}$a(){for(const a of this.K)if("runtime"===a.V){this.G=a;return}throw Error("cannot find runtime DOM handler");}Qb(a){this.fa("debugger","message",a)}Tb(){for(const a of this.K)a.Ra()}static R(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||ka)}static gb(a){ka=!!a}Xa(a){this.aa.add(a);
this.xa()}Xb(a){this.aa.delete(a);0===this.aa.size&&this.Ya()}xa(){-1===this.L&&0<this.aa.size&&(this.L=requestAnimationFrame(this.cc))}Ya(){-1!==this.L&&(cancelAnimationFrame(this.L),this.L=-1)}Rb(){this.L=-1;for(const a of this.aa)a();this.xa()}wa(){this.G.wa()}Ab(){this.mb=!0}ub(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}wb(a){return!this.ub(a)}async I(a){return"cordova"===this.g&&(a.startsWith("file:")||this.Da&&this.wb(a))?(a.startsWith(this.l)&&
(a=a.substr(this.l.length)),a=await this.na(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Nb(a){const b=a.filename;switch(a.as){case "text":return await this.sb(b);case "buffer":return await this.na(b);default:throw Error("unsupported type");}}Sa(a){const b=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(b,f=>{f.file(d,e)},e)})}async sb(a){a=await this.Sa(a);return await ia(a)}ua(){if(C.length&&!(8<=D)){D++;
var a=C.shift();this.Eb(a.filename,a.mc,a.ec)}}na(a){return new Promise((b,d)=>{C.push({filename:a,mc:e=>{D--;this.ua();b(e)},ec:e=>{D--;this.ua();d(e)}});this.ua()})}async Eb(a,b,d){try{const e=await this.Sa(a),f=await B(e);b(f)}catch(e){d(e)}}eb(a){if("entered-fullscreen"===a)c.gb(!0),M(this.G);else if("exited-fullscreen"===a)c.gb(!1),M(this.G);else if("object"===typeof a){const b=a.type;"wrapper-init-response"===b?(this.Oa(a),this.Oa=null):"extension-message"===b?this.fa("runtime","wrapper-extension-message",
a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}Ub(a){this.T({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}T(a){this.H()?window.chrome.webview.postMessage(JSON.stringify(a)):"macos-wkwebview"===this.g&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}Yb(){window.moveTo=(a,b)=>{this.T({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(b)})};window.resizeTo=
(a,b)=>{this.T({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(b)})}}Lb(){return this.H()?new Promise(a=>{this.Oa=a;this.T({type:"wrapper-init"})}):Promise.resolve()}async Db(){const a=[];for(const [b,d]of Object.entries(this.A))a.push(this.Cb(b,d));await Promise.all(a)}async Cb(a,b){if("object"===typeof b)this.A[a]=new Blob([b.str],{type:b.type}),this.ia[a]=b.str;else{let d=await this.Hb(b);d||(d=this.Fb(b));this.A[a]=d}}async Hb(a){try{return await (await fetch(a)).blob()}catch(b){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
b),null}}Fb(a){a=this.Wb(a);return this.Bb(a.data,a.ic)}Wb(a){var b=a.indexOf(",");if(0>b)throw new URIError("expected comma in data: uri");var d=a.substring(b+1);b=a.substring(5,b).split(";");a=b[0]||"";const e=b[2];d="base64"===b[1]||"base64"===e?atob(d):decodeURIComponent(d);return{ic:a,data:d}}Bb(a,b){var d=a.length;let e=d>>2,f=new Uint8Array(d),h=new Uint32Array(f.buffer,0,e),g,k;for(k=g=0;g<e;++g)h[g]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=
3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],{type:b})}};"use strict";const N=self.sa,qa=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),O={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},P={dispatchUserScriptEvent:!0},Q={dispatchRuntimeEvent:!0};function ra(c){return new Promise((a,b)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>b(e);d.rel="stylesheet";d.href=c;document.head.appendChild(d)})}
function ta(c){return new Promise((a,b)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>b(e);d.src=c})}async function ua(c){c=URL.createObjectURL(c);try{return await ta(c)}finally{URL.revokeObjectURL(c)}}function va(c){do{if(c.parentNode&&c.hasAttribute("contenteditable"))return!0;c=c.parentNode}while(c);return!1}const wa=new Set(["input","textarea","datalist","select"]),za=new Set(["canvas","body","html"]);
function R(c){c.target.tagName&&za.has(c.target.tagName.toLowerCase())&&c.preventDefault()}function S(c){c.target.tagName&&c.target.classList.contains("c3htmlwrap")&&c.preventDefault()}function Aa(c){(c.metaKey||c.ctrlKey)&&c.preventDefault()}
self.C3_GetSvgImageSize=async function(c){c=await ua(c);if(0<c.width&&0<c.height)return[c.width,c.height];c.style.position="absolute";c.style.left="0px";c.style.top="0px";c.style.visibility="hidden";document.body.appendChild(c);const a=c.getBoundingClientRect();document.body.removeChild(c);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(c,a,b,d,e){c=await ua(c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(c,0,0,a,b);return f};
let T=!1;document.addEventListener("pause",()=>T=!0);document.addEventListener("resume",()=>T=!1);function J(c){c.addEventListener("selectstart",R);c.addEventListener("gesturehold",R);c.addEventListener("pointerdown",R)}function L(c){c.addEventListener("selectstart",S);c.addEventListener("gesturehold",S);c.addEventListener("touchstart",S)}function na(c){c.kb=!0;c.Fa=c.h.u();c.Z=c.h.o()}
function M(c){if(!c.s){var a=N.R();a&&"any"!==c.Ma&&Ba(c);n(c,"fullscreenchange",{isFullscreen:a,innerWidth:c.u(),innerHeight:c.o()})}}async function Ca(c){await Promise.all(c.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Da(c){var a=c.imageBitmapOpts;c=await self.C3_RasterSvgImageBlob(c.blob,c.imageWidth,c.imageHeight,c.surfaceWidth,c.surfaceHeight);a=a?await createImageBitmap(c,a):await createImageBitmap(c);return{imageBitmap:a,transferables:[a]}}async function Ea(c){return await self.C3_GetSvgImageSize(c.blob)}function Fa(c){window.c3_postToMessagePort&&(c.from="runtime",window.c3_postToMessagePort(c))}
function Ga(c){self.setTimeout(()=>{c.jb=!0},1E3);"cordova"===c.h.g?(document.addEventListener("pause",()=>U(c,!0)),document.addEventListener("resume",()=>U(c,!1))):document.addEventListener("visibilitychange",()=>U(c,"hidden"===document.visibilityState));c.ja=!("hidden"!==document.visibilityState&&!T);return{isSuspended:c.ja}}
function Ha(c){c.ib||(c.ib=!0,window.addEventListener("deviceorientation",a=>{c.s||n(c,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},O)}),window.addEventListener("deviceorientationabsolute",a=>{c.s||n(c,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},O)}))}
function Ia(c){c.hb||(c.hb=!0,window.addEventListener("devicemotion",a=>{if(!c.s){var b=null,d=a.acceleration;d&&(b={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});n(c,"devicemotion",{acceleration:b,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},O)}}))}async function Ja(c){await ra(c.url)}
function Ka(c,a){c.lb=a.message;-1===c.Aa&&(c.Aa=setTimeout(()=>{c.Aa=-1;const b=document.getElementById("exportToVideoMessage");b&&(b.textContent=c.lb)},250))}function V(c,a){console.warn("[Construct] Fullscreen request failed: ",a);n(c,"fullscreenerror",{isFullscreen:N.R(),innerWidth:c.u(),innerHeight:c.o()})}
function U(c,a){c.ja!==a&&((c.ja=a)?c.h.Ya():c.h.xa(),n(c,"visibilitychange",{hidden:a}),!a&&c.h.S()&&(c=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(c,50),setTimeout(c,100),setTimeout(c,250),setTimeout(c,500)))}
function La(c,a,b){"Backspace"===b.key&&R(b);"nwjs"===c.h.g&&"u"===b.key&&(b.ctrlKey||b.metaKey)&&b.preventDefault();if(!c.s){var d=qa.get(b.code)||b.code;r(c,a,{code:d,key:b.key,which:b.which,repeat:b.repeat,altKey:b.altKey,ctrlKey:b.ctrlKey,metaKey:b.metaKey,shiftKey:b.shiftKey,timeStamp:b.timeStamp},O)}}
function W(c,a,b,d){c.s||b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents||r(c,a,{button:b.button,buttons:b.buttons,clientX:b.clientX,clientY:b.clientY+c.C,pageX:b.pageX,pageY:b.pageY+c.C,movementX:b.movementX||0,movementY:b.movementY||0,timeStamp:b.timeStamp},d)}
function X(c,a,b){if(!c.s){var d=0;"mouse"===b.pointerType&&(d=c.Ia);r(c,a,{pointerId:b.pointerId,pointerType:b.pointerType,button:b.button,buttons:b.buttons,lastButtons:d,clientX:b.clientX,clientY:b.clientY+c.C,pageX:b.pageX,pageY:b.pageY+c.C,movementX:b.movementX||0,movementY:b.movementY||0,width:b.width||0,height:b.height||0,pressure:b.pressure||0,tangentialPressure:b.tangentialPressure||0,tiltX:b.tiltX||0,tiltY:b.tiltY||0,twist:b.twist||0,timeStamp:b.timeStamp},O);"mouse"===b.pointerType&&(c.Ia=
b.buttons)}}function Y(c,a,b){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";c.C=0;if(0<b){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-b)/2,a>b&&(a=b),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,c.C=a))}}
function Ma(c,a,b,d){const e=c.u(),f=c.o();c.N=-1;e!=a||f!=b?n(c,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:N.R(),cssDisplayMode:c.h.ra()}):10>d&&Na(c,e,f,d+1)}function Na(c,a,b,d){-1!==c.N&&clearTimeout(c.N);c.N=setTimeout(()=>Ma(c,a,b,d),48)}
function Ba(c){c=c.Ma;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(c).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(c):screen.webkitLockOrientation?a=screen.webkitLockOrientation(c):screen.mozLockOrientation?a=screen.mozLockOrientation(c):screen.msLockOrientation&&(a=screen.msLockOrientation(c));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Oa(c){return!c||c===document||c===window||c===document.body||"canvas"===c.tagName.toLowerCase()}
N.Qa(class extends self.Ua{constructor(c){super(c,"runtime");this.kb=!1;this.N=-1;this.Ma="any";this.ja=this.hb=this.ib=!1;this.ka=document.createElement("div");this.ka.className="c3-screen-reader-text";this.ka.setAttribute("aria-live","polite");document.body.appendChild(this.ka);this.D=null;this.s=!1;this.lb="";this.Aa=-1;this.jb=!1;this.Fa=c.u();this.Z=c.o();this.C=this.ba=0;c.i("runtime","invoke-download",b=>{const d=b.url;b=b.filename;const e=document.createElement("a"),f=document.body;e.textContent=
b;e.href=d;e.download=b;f.appendChild(e);e.click();f.removeChild(e)});c.i("runtime","load-webfonts",b=>Ca(b));c.i("runtime","raster-svg-image",b=>Da(b));c.i("runtime","get-svg-image-size",b=>Ea(b));c.i("runtime","set-target-orientation",b=>{this.Ma=b.targetOrientation});c.i("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});c.i("runtime","post-to-debugger",b=>Fa(b));c.i("runtime","go-to-script",b=>Fa(b));c.i("runtime","before-start-ticking",()=>Ga(this));c.i("runtime","debug-highlight",
b=>{if(b.show){this.D||(this.D=document.createElement("div"),this.D.id="inspectOutline",document.body.appendChild(this.D));var d=this.D;d.style.display="";d.style.left=b.left-1+"px";d.style.top=b.top-1+"px";d.style.width=b.width+2+"px";d.style.height=b.height+2+"px";d.textContent=b.name}else this.D&&(this.D.style.display="none")});c.i("runtime","enable-device-orientation",()=>Ha(this));c.i("runtime","enable-device-motion",()=>Ia(this));c.i("runtime","add-stylesheet",b=>Ja(b));c.i("runtime","script-create-worker",
b=>{const d=b.port2;(new Worker(b.url,b.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});c.i("runtime","alert",b=>{alert(b.message)});c.i("runtime","screen-reader-text",b=>{var d=b.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+b.id,d.textContent=b.text,this.ka.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+b.id))?d.textContent=b.text:console.warn(`[Construct] Missing screen reader text with id ${b.id}`):"release"===d?(d=document.getElementById("c3-sr-"+
b.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${b.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});c.i("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});c.i("runtime","set-exporting-to-video",b=>{this.s=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=b.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.h.tb().style.display="";this.h.Ab()});c.i("runtime","export-to-video-progress",b=>Ka(this,b));c.i("runtime","exported-to-video",b=>{window.dc({type:"exported-video",arrayBuffer:b.arrayBuffer,contentType:b.contentType,time:b.time})});c.i("runtime","exported-to-image-sequence",b=>{window.dc({type:"exported-image-sequence",blobArr:b.blobArr,time:b.time,gif:b.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",b=>{const d=b.target;a.has(d.tagName.toLowerCase())||
va(d)||b.preventDefault()});window.addEventListener("selectstart",R);window.addEventListener("gesturehold",R);window.addEventListener("touchstart",R,{passive:!1});window.addEventListener("pointerdown",R,{passive:!1});this.Ia=0;window.addEventListener("mousedown",b=>{1===b.button&&b.preventDefault()});window.addEventListener("mousewheel",Aa,{passive:!1});window.addEventListener("wheel",Aa,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.s&&this.kb){var b=this.u();var d=this.o();if(this.h.Va()){if(this.jb){if(this.Fa===
b&&d<this.Z){this.ba=this.Z-d;Y(this,this.Z,this.ba);b=void 0;break a}0<this.ba&&(this.ba=0,Y(this,d,this.ba))}this.Fa=b;this.Z=d}n(this,"window-resize",{innerWidth:b,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:N.R(),cssDisplayMode:this.h.ra()});this.h.S()&&(-1!==this.N&&clearTimeout(this.N),Ma(this,b,d,0))}b=void 0}return b});window.addEventListener("fullscreenchange",()=>M(this));window.addEventListener("webkitfullscreenchange",()=>M(this));window.addEventListener("mozfullscreenchange",
()=>M(this));window.addEventListener("fullscreenerror",b=>V(this,b));window.addEventListener("webkitfullscreenerror",b=>V(this,b));window.addEventListener("mozfullscreenerror",b=>V(this,b));if(c.S()){let b=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>b&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);b=d});document.documentElement.setAttribute("ioswebview","")}this.Ha=new Set;this.bc=new WeakSet;this.$b=!1}Ra(){window.addEventListener("focus",
()=>{n(this,"window-focus",null,Q)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(b){a=!1}n(this,"window-blur",{parentHasFocus:a},Q);this.Ia=0});window.addEventListener("focusin",a=>{a=a.target;(wa.has(a.tagName.toLowerCase())||va(a))&&n(this,"keyboard-blur",null,Q)});window.addEventListener("keydown",a=>La(this,"keydown",a));window.addEventListener("keyup",a=>La(this,"keyup",a));window.addEventListener("mousedown",a=>W(this,"mousedown",a,P));
window.addEventListener("mousemove",a=>W(this,"mousemove",a,P));window.addEventListener("mouseup",a=>W(this,"mouseup",a,P));window.addEventListener("dblclick",a=>W(this,"dblclick",a,O));window.addEventListener("wheel",a=>{this.s||n(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.C,pageX:a.pageX,pageY:a.pageY+this.C,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},O)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();Oa(a.target)&&
document.activeElement&&!Oa(document.activeElement)&&document.activeElement.blur();X(this,"pointerdown",a)});this.h.m&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?window.addEventListener("pointerrawupdate",a=>{X(this,"pointermove",a)}):window.addEventListener("pointermove",a=>X(this,"pointermove",a));window.addEventListener("pointerup",a=>X(this,"pointerup",a));window.addEventListener("pointercancel",a=>X(this,"pointercancel",a));const c=()=>this.wa();window.addEventListener("pointerup",
c,!0);window.addEventListener("touchend",c,!0);window.addEventListener("click",c,!0);window.addEventListener("keydown",c,!0);window.addEventListener("gamepadconnected",c,!0);this.h.vb()&&!this.h.Va()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Y(this,this.o(),navigator.virtualKeyboard.boundingRect.height)}));this.h.S()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}u(){return this.h.u()}o(){return this.h.o()}wa(){var c=
[...this.Ha];this.Ha.clear();if(!this.$b)for(const a of c)(c=a.play())&&c.catch(()=>{this.bc.has(a)||this.Ha.add(a)})}});"use strict";async function la(c){if(c.Zb)throw Error("already initialised");c.Zb=!0;var a=c.B.va(("playable-ad"===c.B.g?c.B.M:"")+"dispatchworker.js");c.za=await c.B.oa(a,c.U,{name:"DispatchWorker"});a=new MessageChannel;c.Ca=a.port1;c.za.postMessage({type:"_init","in-port":a.port2},[a.port2]);c.Ja=await oa(c)}function ma(c){return[c.Ca,c.Ja]}
async function oa(c){const a=c.ob.length;var b=c.B.va(("playable-ad"===c.B.g?c.B.M:"")+"jobworker.js");b=await c.B.oa(b,c.U,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;c.za.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);c.ob.push(b);return e.port1}
self.yb=class{constructor(c){this.B=c;this.U=c.l;this.U="preview"===c.g?this.U+"workers/":this.U+c.M;this.ac=Math.min(navigator.hardwareConcurrency||2,16);this.za=null;this.ob=[];this.Ja=this.Ca=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.sa({nc:!0,oc:"workermain.js",P:["scripts/c3runtime.js"],la:[],Pa:"",kc:"scripts/",ma:[],rb:"html5"}));"use strict";function Z(c){c.stopPropagation()}
self.sa.Qa(class extends self.pa{constructor(c){super(c)}Ta(c,a){const b=document.createElement("input");b.type="range";b.style.position="absolute";b.style.userSelect="none";b.style.webkitUserSelect="none";b.addEventListener("pointerdown",Z);b.addEventListener("pointermove",Z);b.addEventListener("pointerrawupdate",Z);b.addEventListener("pointerup",Z);b.addEventListener("mousedown",Z);b.addEventListener("mouseup",Z);b.addEventListener("keydown",Z);b.addEventListener("keyup",Z);b.addEventListener("contextmenu",
d=>d.preventDefault());b.addEventListener("click",()=>{var d;d||(d={});d.elementId=c;r(this,"click",d)});b.addEventListener("change",()=>u(this,"change",c,{value:parseFloat(b.value)}));b.addEventListener("input",()=>u(this,"input",c,{value:parseFloat(b.value)}));a.id&&(b.id=a.id);a.className&&(b.className=a.className);this.ta(b,a);return b}ta(c,a){c.max=a.max;c.min=a.min;c.step=a.step;c.value=a.value;c.disabled=!a.isEnabled;c.title=a.title}});
